### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by vikram162** [sivalabs/localstack-spring-boot-starter#15]
Hello @sivaprasadreddy, can you please create a new release/tag which includes the fix for [issue 11](https://github.com/sivalabs/localstack-spring-boot-starter/pull/12)

Thank you

**Comment by sivaprasadreddy** [comment]
Hi @vikram162 
I have released the new version 0.0.3.

```
<dependency>
	<groupId>io.github.sivalabs</groupId>
	<artifactId>localstack-spring-boot-starter</artifactId>
	<version>${localstack-starter.version}</version>
</dependency>
```
